services:
  ollama-agent:
    build: .
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./vector_db:/vector_db
      - ./ollama_rag:/ollama_rag
      - ./config/:/config/
    depends_on:
      - qdrant
    ports:
      - "8001:8000"

    environment:
      - HOST_MACHINE_ADDRESS=host.docker.internal

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    command: ["./qdrant", "--config-path", "config/qdrant.yaml"]
    volumes:
      - ./vector_db:/qdrant/storage
      - ./config/qdrant.yaml:/qdrant/config/qdrant.yaml
    ports:
      - "6333:6333"
      - "6334:6334"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"
    deploy:
      resources:
        limits:
          memory: 10Gb


# network for services
